In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

house = pd.read_csv('data/BostonHousing.csv')

lstat = house["lstat"]
medv = house["medv"]
lstat = np.array(lstat).reshape(506,1)
medv = np.array(medv).reshape(506,1)

train_X, test_X, train_y, test_y = train_test_split(lstat, medv, test_size=0.3, random_state=1234)  

model = LinearRegression()
model.fit(train_X, train_y)
pred_y = model.predict(test_X)
# print(pred_y)
print('Coefficients: {0:.2f}, Intercept {1:.3f}'.format(model.coef_[0][0], model.intercept_[0])) 

q3_test_X = [[2.0], [3.0], [4.0]]
print(model.predict(q3_test_X))

print('Mean squared error: {0:.2f}'.format(mean_squared_error(test_y, pred_y)))
print('Coefficient of determination: %.2f'% r2_score(test_y, pred_y))

Coefficients: -0.94, Intercept 34.321
[[32.44550746]
 [31.50768979]
 [30.56987212]]
Mean squared error: 40.44
Coefficient of determination: 0.56


In [43]:

house_X = house[['lstat','ptratio','tax', 'rad']]
house_y = house['medv']

house_X = np.array(house_X).reshape(506,4)
house_y = np.array(house_y).reshape(506,1)

# 데이터셋 train:test = 7:3, random_state = 1234
train_X, test_X, train_y, test_y = train_test_split(house_X, house_y, test_size=0.3,random_state=1234)

model = LinearRegression()
model.fit(train_X, train_y)
pred_y = model.predict(test_X)
# print(pred_y)
print('Coefficients: {0:.2f}, Intercept {1:.3f}'.format(model.coef_[0][0], model.intercept_[0])) 

q7_test_X = np.array([[2.0, 14, 296, 1],[3.0, 15, 222, 2],[4.0, 15, 250, 3]]).reshape(3,4)
print(model.predict(q7_test_X))

print('Mean squared error: {0:.2f}'.format(mean_squared_error(test_y, pred_y)))
print('Coefficient of determination: %.2f'% r2_score(test_y, pred_y))

Coefficients: -0.81, Intercept 59.262
[[35.49774089]
 [34.90871561]
 [34.01764254]]
Mean squared error: 34.49
Coefficient of determination: 0.63


In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

ucla = pd.read_csv("data/ucla_admit.csv")

ucla_X = ucla[["gre", "gpa", "rank"]]
ucla_y = ucla["admit"]

# ucla_X = np.array(ucla_X).reshape(400,3)
# ucla_y = np.array(ucla_y).reshape(400,1)

train_X, test_X, train_y, test_y = train_test_split(ucla_X, ucla_y, test_size=0.3, random_state=1234) # train : test = 7 : 3

model = LogisticRegression()
model.fit(train_X, train_y)

# Q11
pred_y = model.predict(test_X)
acc = accuracy_score(test_y, pred_y)
print('Test Accuracy : {0:3f}'.format(acc))
pred_y = model.predict(train_X)
acc = accuracy_score(train_y, pred_y)
print('Train Accuracy : {0:3f}'.format(acc))

# Q12
q12_test_X = np.array([[400, 3.5, 5], [550, 3.8, 2], [700, 4.0, 2]]).reshape(3,3)
print(model.predict(q12_test_X))

# Q13
ucla_X = ucla[["gre","gpa"]]
ucla_y = ucla["admit"]
train_X, test_X, train_y, test_y = train_test_split(ucla_X, ucla_y, test_size=0.3, random_state=1234) # train : test = 7 : 3
model.fit(train_X, train_y)
pred_y = model.predict(test_X)
print(pred_y)

# Q14
pred_y = model.predict(test_X)
acc = accuracy_score(test_y, pred_y)
print('Test Accuracy : {0:3f}'.format(acc))
pred_y = model.predict(train_X)
acc = accuracy_score(train_y, pred_y)
print('Train Accuracy : {0:3f}'.format(acc))

Test Accuracy : 0.741667
Train Accuracy : 0.671429
[0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
Test Accuracy : 0.825000
Train Accuracy : 0.625000


c:\Users\NBH\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
